// <auto-generated />
using System;
using Hehehe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hehehe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231023055041_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hehehe.Models.Expiration", b =>
                {
                    b.Property<DateTime>("ExactMoment")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "exact_moment");

                    b.Property<int>("MomentType")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "moment_type");

                    b.ToTable("Expiration");
                });

            modelBuilder.Entity("Hehehe.Models.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("ExpirationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "plan_name");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
