name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEB_APP_NAME: dateapiv1
  AZURE_WEB_APP_PACKAGE_PATH: './publish'
  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./Date.API/Date.API.sln

      - name: Build
        run: dotnet build ./Date.API/Date.API.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Date.API/Date.API.sln --configuration Release --no-build --output '${{ env.AZURE_WEB_APP_PACKAGE_PATH }}'
      
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEB_APP_PACKAGE_PATH }}
